apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jenkins-helm-manager
  namespace: jenkins
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-helm-manager-binding
  namespace: jenkins
subjects:
- kind: ServiceAccount
  name: jenkins
  namespace: jenkins
roleRef:
  kind: Role
  name: jenkins-helm-manager
  apiGroup: rbac.authorization.k8s.io