apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jenkins-helm-manager
  namespace: jenkins
rules:
- apiGroups: ["", "apps", "extensions"]
  # Add "serviceaccounts" to this list
  resources: ["configmaps", "secrets", "services", "statefulsets", "deployments", "pods", "serviceaccounts"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-helm-manager-binding
  namespace: jenkins
subjects:
- kind: ServiceAccount
  name: jenkins
  namespace: jenkins
roleRef:
  kind: Role
  name: jenkins-helm-manager
  apiGroup: rbac.authorization.k8s.io