controller:
  agentHost: "jenkins-agent.jenkins.svc.cluster.local"
  installPlugins:
    - "job-dsl:1.85"

  # This section is for Jenkins Configuration as Code (JCasC)
  JCasC:
    # This new line disables the chart's default JCasC scripts
    defaultConfig: false

    # We will define our configuration scripts here
    configScripts:
      # You can name this anything you like, e.g., "my-k8s-config"
      kubernetes-cloud: |
        jenkins:
          clouds:
            - kubernetes:
                # The name of your cloud configuration in the Jenkins UI
                name: "kubernetes"
                # The internal URL for the Jenkins controller
                jenkinsUrl: "http://jenkins.jenkins.svc.cluster.local:8080"
                jenkinsTunnel: "jenkins-agent.jenkins.svc.cluster.local:50000"
                # Here we define the pod templates
                templates:
                  - name: "jnlp-agent"
                    label: "jnlp-agent"
                    containers:
                      - name: "jnlp"
                        image: "jenkins/inbound-agent:latest"
                        workingDir: "/home/jenkins/agent"
                        alwaysPullImage: true
                  - name: "helm-agent"
                    label: "helm-agent"
                    # This tells the pod to use the 'jenkins' service account,
                    # which the Helm chart already created with some permissions.
                    serviceAccount: "jenkins"
                    containers:
                      - name: "jnlp"
                        image: "jenkins/inbound-agent:latest"
                        workingDir: "/home/jenkins/agent"
                        alwaysPullImage: true
                      # This container has kubectl and helm installed
                      - name: "helm"
                        image: "alpine/k8s:1.27.3"
                        command: "cat"
                        ttyEnabled: true
                  - name: "kaniko-agent"
                    label: "kaniko-agent"
                    containers:
                      - name: "jnlp"
                        image: "jenkins/inbound-agent:latest"
                        workingDir: "/home/jenkins/agent"
                        alwaysPullImage: true
                      - name: "kaniko"
                        image: "gcr.io/kaniko-project/executor:debug"
                        imagePullPolicy: "Always"
                        command: "cat"
                        ttyEnabled: true
      seed-job: |
        jobs:
          - script: >
              freeStyleJob('seed-job') {
                description('This job creates all other jobs from the repository.')
                label('jnlp-agent')
                scm {
                  git {
                    remote {
                      url('https://github.com/0903lokchan/cicd-lab-monorepo.git')
                    }
                    branch('*/main')
                  }
                }
                steps {
                  jobDsl {
                    // Tell the job where to find the DSL script(s)
                    targets('.jenkins/jobs.groovy')
                  }
                }
              }
      jenkins-description: |
        jenkins:
          systemMessage: "This Jenkins instance is managed by a self-deployment pipeline! 🚀"
