controller:
  # This section is for Jenkins Configuration as Code (JCasC)
  JCasC:
    # This new line disables the chart's default JCasC scripts
    defaultConfig: false

    # We will define our configuration scripts here
    configScripts:
      # You can name this anything you like, e.g., "my-k8s-config"
      kubernetes-cloud: |
        jenkins:
          clouds:
            - kubernetes:
                # The name of your cloud configuration in the Jenkins UI
                name: "kubernetes"
                # The internal URL for the Jenkins controller
                jenkinsUrl: "http://jenkins.jenkins.svc.cluster.local:8080"
                # Here we define the pod templates
                templates:
                  - name: "jnlp-agent"
                    label: "jnlp-agent"
                    containers:
                      - name: "jnlp"
                        image: "jenkins/inbound-agent:latest"
                        workingDir: "/home/jenkins/agent"
                        alwaysPullImage: true
